TopSpeed.Web/Areas/Admin/Controllers/VehicleTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using TopSpeed.Application.ApplicationConstants;
using TopSpeed.Application.Contracts.Presistence;
using TopSpeed.Domain.Models;
using TopSpeed.Infrastructure.Common;

namespace TopSpeed.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = CustomRole.MasterAdmin + "," + CustomRole.Admin)]
    public class VehicleTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public VehicleTypeController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;

        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<VehicleType> vehicleTypes = await _unitOfWork.VehicleType.GetAllAsync();

            return View(vehicleTypes);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(VehicleType vehicleType)
        {

            if (ModelState.IsValid)
            {
                await _unitOfWork.VehicleType.Create(vehicleType);
                await _unitOfWork.SaveAsync();

                TempData["success"] = CommonMessage.RecordCreated;

                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            VehicleType vehicleType = await _unitOfWork.VehicleType.GetByIdAsync(id);

            return View(vehicleType);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            VehicleType vehicleType = await _unitOfWork.VehicleType.GetByIdAsync(id);

            return View(vehicleType);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VehicleType vehicleType)
        {
           
            if (ModelState.IsValid)
            {
                await _unitOfWork.VehicleType.Update(vehicleType);
                await _unitOfWork.SaveAsync();

                TempData["warning"] = CommonMessage.RecordUpdated;

                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            VehicleType vehicleType = await _unitOfWork.VehicleType.GetByIdAsync(id);

            return View(vehicleType);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(VehicleType vehicleType)
        {
            
            await _unitOfWork.VehicleType.Delete(vehicleType);
            await _unitOfWork.SaveAsync();

            TempData["error"] = CommonMessage.RecordDeleted;

            return RedirectToAction(nameof(Index));
        }
    }
}

TopSpeed.Web/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TopSpeed.Application.ApplicationConstants;
using TopSpeed.Application.Contracts.Presistence;
using TopSpeed.Domain.Models;
using TopSpeed.Infrastructure.Common;

namespace TopSpeed.Web.Controllers
{
    public class BrandController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BrandController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;

        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<Brand> brands = await _unitOfWork.Brand.GetAllAsync();

            return View(brands);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Brand brand)
        {
            string webRootPath = _webHostEnvironment.WebRootPath;

            var file = HttpContext.Request.Form.Files;

            if (file.Count > 0)
            {
                string newFileName = Guid.NewGuid().ToString();

                var upload = Path.Combine(webRootPath, @"images\brand");

                var extension = Path.GetExtension(file[0].FileName);

                using (var fileStream = new FileStream(Path.Combine(upload, newFileName + extension), FileMode.Create))
                {
                    file[0].CopyTo(fileStream);
                }

                brand.BrandLogo = @"\images\brand\" + newFileName + extension;
            }

            if (ModelState.IsValid)
            {
                await _unitOfWork.Brand.Create(brand);
                await _unitOfWork.SaveAsync();

                TempData["success"] = CommonMessage.RecordCreated;

                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            Brand brand = await _unitOfWork.Brand.GetByIdAsync(id);

            return View(brand);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            Brand brand = await _unitOfWork.Brand.GetByIdAsync(id);

            return View(brand);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Brand brand)
        {
            string webRootPath = _webHostEnvironment.WebRootPath;

            var file = HttpContext.Request.Form.Files;

            if (file.Count > 0)
            {
                string newFileName = Guid.NewGuid().ToString();

                var upload = Path.Combine(webRootPath, @"images\brand");

                var extension = Path.GetExtension(file[0].FileName);

                //delete old image
                var objFromDb = await _unitOfWork.Brand.GetByIdAsync(brand.Id);

                if (objFromDb.BrandLogo != null)
                {
                    var oldImagePath = Path.Combine(webRootPath, objFromDb.BrandLogo.Trim('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }


                using (var fileStream = new FileStream(Path.Combine(upload, newFileName + extension), FileMode.Create))
                {
                    file[0].CopyTo(fileStream);
                }

                brand.BrandLogo = @"\images\brand\" + newFileName + extension;
            }


            if (ModelState.IsValid)
            {
                await _unitOfWork.Brand.Update(brand);
                await _unitOfWork.SaveAsync();

                TempData["warning"] = CommonMessage.RecordUpdated;

                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            Brand brand = await _unitOfWork.Brand.GetByIdAsync(id);

            return View(brand);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Brand brand)
        {
            string webRootPath = _webHostEnvironment.WebRootPath;

            if (!string.IsNullOrEmpty(brand.BrandLogo))
            {
                //delete old image
                var objFromDb = await _unitOfWork.Brand.GetByIdAsync(brand.Id);

                if (objFromDb.BrandLogo != null)
                {
                    var oldImagePath = Path.Combine(webRootPath, objFromDb.BrandLogo.Trim('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
            }

            await _unitOfWork.Brand.Delete(brand);
            await _unitOfWork.SaveAsync();

            TempData["error"] = CommonMessage.RecordDeleted;

            return RedirectToAction(nameof(Index));
        }
    }
}

TopSpeed.Web/Areas/Admin/Views/VehicleType/Create.cshtml
@model VehicleType

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-uppercase text-center">Create Vehicle Type</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 border-1 border">
            <form method="post" enctype="multipart/form-data">
                <div class="mb-3">
                    <label asp-for="@Model.Name" class="form-label"></label>
                    <input asp-for="@Model.Name" class="form-control"/>
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <a asp-area="Admin" asp-controller="VehicleType" asp-action="Index" class="btn btn-danger">Back</a>
                    <button type="submit" class="btn btn-success">Create</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

TopSpeed.Web/Areas/Admin/Views/VehicleType/Delete.cshtml
@model VehicleType

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-uppercase text-center">Delete Vehicle Type</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 border-1 border">
            <form method="post" enctype="multipart/form-data">
                <input asp-for="@Model.Id" hidden/>
                <div class="mb-3">
                    <label asp-for="@Model.Name" class="form-label"></label>
                    <input asp-for="@Model.Name" class="form-control" disabled/>
                </div>
                <div class="mb-3">
                    <a asp-controller="Brand" asp-action="Index" class="btn btn-warning">Back</a>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>

TopSpeed.Web/Areas/Admin/Views/VehicleType/Details.cshtml
@model VehicleType

<div class="container">
    <div class="card">
        <div class="card-header text-center text-uppercase">
            Vehicle Type Details
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-4">
                            <p class="card-text text-uppercase"><strong>Id</strong></p>
                        </div>
                        <div class="col-md-8">
                            <p class="card-text">: @Model.Id</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <p class="card-text text-uppercase"><strong>Vehicle Type</strong></p>
                        </div>
                        <div class="col-md-8">
                            <p class="card-text">: @Model.Name</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 text-center">
                    <a asp-area="Admin" asp-controller="VehicleType" asp-action="Index" class="btn btn-danger">Back</a>
                </div>
            </div>
        </div>
    </div>
</div>

TopSpeed.Web/Areas/Admin/Views/VehicleType/Edit.cshtml
@model VehicleType

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-uppercase text-center">Edit Vehicle Type</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 border-1 border">
            <form method="post" enctype="multipart/form-data">
                <input asp-for="@Model.Id" hidden />
                <div class="mb-3">
                    <label asp-for="@Model.Name" class="form-label"></label>
                    <input asp-for="@Model.Name" class="form-control" />
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <a asp-area="Admin" asp-controller="VehicleType" asp-action="Index" class="btn btn-danger">Back</a>
                    <button type="submit" class="btn btn-warning">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

TopSpeed.Web/Areas/Admin/Views/VehicleType/Index.cshtml
@model List<VehicleType>

@{
    int count = 0;
}

<div class="container">
    <div class="row mb-4">
        <div class="col-md-6 text-uppercase">
            <h2>Vehicle Type List</h2>
        </div>
        <div class="col-md-6 text-end">
            <a asp-area="Admin" asp-controller="VehicleType" asp-action="Create" class="btn btn-primary"><i class="bi bi-plus-circle"></i> Create</a>
        </div>
    </div>
    <hr />
    @if (Model.Count() > 0)
    {
        <table id="table" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th class="text-center">S.No</th>
                    <th class="text-center">Name</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-center" width="20%">@(++count)</td>
                        <td class="" width="60%">@item.Name</td>
                        <td class="d-flex align-items-center justify-content-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-area="Admin" asp-controller="VehicleType" asp-action="Details" asp-route-id="@item.Id"
                                   class="btn btn-info" data-toggle="tooltip" data-placement="top" title="Details">
                                    <i class="bi bi-info-circle"></i>
                                </a>
                                <a asp-area="Admin" asp-controller="VehicleType" asp-action="Edit" asp-route-id="@item.Id"
                                   class="btn btn-warning" data-toggle="tooltip" data-placement="top" title="Edit">
                                    <i class="bi bi-pencil-square"></i>
                                </a>
                                <a asp-area="Admin" asp-controller="VehicleType" asp-action="Delete" asp-route-id="@item.Id"
                                   class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Delete">
                                    <i class="bi bi-trash"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    }
    else
    {
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="text-center text-uppercase text-warning pt-4">No Records to Show</h2>
                </div>
            </div>
        </div>
    }

</div>

@section Scripts{
    <script>
        $('.table').DataTable();
    </script>
}